[build]
  command = "npx pnpm install --store-dir=.pnpm-store --no-frozen-lockfile && npx pnpm docs:build"
  publish = "offical/.vitepress/dist"

[build.environment]
  NPM_FLAGS="--version"

# Redirect with a 302
[[redirects]]
from = "/"
to = "https://empjs.dev/"
status = 302
