[build]
  command = "npx pnpm install --store-dir=.pnpm-store --no-frozen-lockfile"
  publish = "package.json"

[build.environment]
  NPM_FLAGS="--version"

[[redirects]]
from = "/"
to = "https://empjs.dev/"
status = 302
