packages:
  - packages/**
  - projects/**
  - '!**/test/**'
  - website

ignoredBuiltDependencies:
  - '@biomejs/biome'
  - '@parcel/watcher'
  - '@swc/core'
  - '@tailwindcss/oxide'
  - core-js
  - core-js-bundle
  - core-js-pure
  - esbuild
  - fsevents
