name: mf-vue2-showcase CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'projects/vue-2-project/**'
      - 'projects/vue-2-base/**'
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV

      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --no-frozen-lockfile
      - run: pnpm emp-plugin-build
        
      - run: mkdir -p ${{ github.workspace }}/.output/app && mkdir -p ${{ github.workspace }}/.output/host
      - run: ls
      - run: echo ${{ github.workspace }}
      - run: pnpm cloudflare:mf-vue2

      - run: cp -r ${{ github.workspace }}/projects/vue-2-project/dist/* ${{ github.workspace }}/.output/app
      - run: cp -r ${{ github.workspace }}/projects/vue-2-base/dist/* ${{ github.workspace }}/.output/host
      - run: ls .output

      - name: Publish to Cloudflare Pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: a1de09ceedba10d3b70d54cc47e6ff25
          projectName: mf-vue2
          directory: .output
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          wranglerVersion: '3'